[package]
name = "call-her"
version = "0.1.0"
description = "Tiny desktop reminder to check in with her"
authors = ["you"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "call_her_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-notification = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
